extern int charToInt(char);
extern int compare(char*, char*);
extern void reverse(sds);
extern sds intToString(int);
extern sds prepend(char*, sds);
extern sds substr(sds, int, int);
extern sds padZeroes(char*, char*);
extern sds addNumbers(sds, sds);
extern sds subtractNumbers(sds, sds);
extern sds multiplyNumbers(sds, sds);